<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AttributeDefinitionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $attributes = [
            // General Attributes (All Categories)
            [
                'name' => 'Brand',
                'slug' => 'brand',
                'display_name' => 'Brand',
                'description' => 'Product manufacturer or brand name',
                'data_type' => 'text',
                'unit' => null,
                'applicable_categories' => ['all'],
                'attribute_group' => 'general',
                'sort_order' => 10,
                'is_filterable' => true,
                'is_comparable' => true,
                'is_required' => true,
            ],
            [
                'name' => 'Model',
                'slug' => 'model',
                'display_name' => 'Model',
                'description' => 'Product model number or name',
                'data_type' => 'text',
                'unit' => null,
                'applicable_categories' => ['all'],
                'attribute_group' => 'general',
                'sort_order' => 20,
                'is_filterable' => true,
                'is_comparable' => true,
                'is_required' => false,
            ],
            [
                'name' => 'Weight',
                'slug' => 'weight',
                'display_name' => 'Weight',
                'description' => 'Product weight',
                'data_type' => 'decimal',
                'unit' => 'kg',
                'applicable_categories' => ['all'],
                'attribute_group' => 'physical',
                'sort_order' => 30,
                'is_filterable' => false,
                'is_comparable' => true,
            ],
            [
                'name' => 'Dimensions',
                'slug' => 'dimensions',
                'display_name' => 'Dimensions',
                'description' => 'Product dimensions (L x W x H)',
                'data_type' => 'text',
                'unit' => 'mm',
                'applicable_categories' => ['all'],
                'attribute_group' => 'physical',
                'sort_order' => 40,
                'is_filterable' => false,
                'is_comparable' => true,
            ],

            // Power & Performance
            [
                'name' => 'Power Consumption',
                'slug' => 'power_consumption',
                'display_name' => 'Power Consumption',
                'description' => 'Power consumption in watts',
                'data_type' => 'number',
                'unit' => 'W',
                'applicable_categories' => ['cpu', 'gpu', 'psu', 'motherboard'],
                'attribute_group' => 'performance',
                'sort_order' => 100,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'Base Clock',
                'slug' => 'base_clock',
                'display_name' => 'Base Clock',
                'description' => 'Base operating frequency',
                'data_type' => 'number',
                'unit' => 'MHz',
                'applicable_categories' => ['cpu', 'gpu'],
                'attribute_group' => 'performance',
                'sort_order' => 110,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'Boost Clock',
                'slug' => 'boost_clock',
                'display_name' => 'Boost Clock',
                'description' => 'Maximum boost frequency',
                'data_type' => 'number',
                'unit' => 'MHz',
                'applicable_categories' => ['cpu', 'gpu'],
                'attribute_group' => 'performance',
                'sort_order' => 120,
                'is_filterable' => true,
                'is_comparable' => true,
            ],

            // CPU Specific
            [
                'name' => 'Cores',
                'slug' => 'cores',
                'display_name' => 'Cores',
                'description' => 'Number of CPU cores',
                'data_type' => 'number',
                'unit' => null,
                'applicable_categories' => ['cpu'],
                'attribute_group' => 'performance',
                'sort_order' => 130,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'Threads',
                'slug' => 'threads',
                'display_name' => 'Threads',
                'description' => 'Number of CPU threads',
                'data_type' => 'number',
                'unit' => null,
                'applicable_categories' => ['cpu'],
                'attribute_group' => 'performance',
                'sort_order' => 140,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'Socket',
                'slug' => 'socket',
                'display_name' => 'Socket',
                'description' => 'CPU socket type',
                'data_type' => 'select',
                'unit' => null,
                'possible_values' => ['LGA1700', 'AM4', 'AM5', 'LGA1200', 'sTRX4', 'TR4'],
                'applicable_categories' => ['cpu', 'motherboard'],
                'attribute_group' => 'compatibility',
                'sort_order' => 200,
                'is_filterable' => true,
                'is_comparable' => true,
            ],

            // Memory/Storage
            [
                'name' => 'Capacity',
                'slug' => 'capacity',
                'display_name' => 'Capacity',
                'description' => 'Storage or memory capacity',
                'data_type' => 'number',
                'unit' => 'GB',
                'applicable_categories' => ['ram', 'ssd', 'hdd'],
                'attribute_group' => 'performance',
                'sort_order' => 150,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'Memory Speed',
                'slug' => 'memory_speed',
                'display_name' => 'Memory Speed',
                'description' => 'Memory operating speed',
                'data_type' => 'number',
                'unit' => 'MHz',
                'applicable_categories' => ['ram'],
                'attribute_group' => 'performance',
                'sort_order' => 160,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'Memory Type',
                'slug' => 'memory_type',
                'display_name' => 'Memory Type',
                'description' => 'Type of memory',
                'data_type' => 'select',
                'unit' => null,
                'possible_values' => ['DDR4', 'DDR5', 'GDDR6', 'GDDR6X'],
                'applicable_categories' => ['ram', 'gpu'],
                'attribute_group' => 'compatibility',
                'sort_order' => 210,
                'is_filterable' => true,
                'is_comparable' => true,
            ],

            // GPU Specific
            [
                'name' => 'VRAM',
                'slug' => 'vram',
                'display_name' => 'VRAM',
                'description' => 'Video memory size',
                'data_type' => 'number',
                'unit' => 'GB',
                'applicable_categories' => ['gpu'],
                'attribute_group' => 'performance',
                'sort_order' => 170,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
            [
                'name' => 'CUDA Cores',
                'slug' => 'cuda_cores',
                'display_name' => 'CUDA Cores',
                'description' => 'Number of CUDA cores (NVIDIA)',
                'data_type' => 'number',
                'unit' => null,
                'applicable_categories' => ['gpu'],
                'attribute_group' => 'performance',
                'sort_order' => 180,
                'is_filterable' => true,
                'is_comparable' => true,
            ],

            // Connectivity
            [
                'name' => 'Interface',
                'slug' => 'interface',
                'display_name' => 'Interface',
                'description' => 'Connection interface type',
                'data_type' => 'select',
                'unit' => null,
                'possible_values' => ['PCIe 4.0', 'PCIe 3.0', 'SATA 3', 'NVMe', 'USB 3.0', 'USB-C'],
                'applicable_categories' => ['gpu', 'ssd', 'hdd', 'peripherals'],
                'attribute_group' => 'connectivity',
                'sort_order' => 220,
                'is_filterable' => true,
                'is_comparable' => true,
            ],

            // Form Factor
            [
                'name' => 'Form Factor',
                'slug' => 'form_factor',
                'display_name' => 'Form Factor',
                'description' => 'Physical form factor',
                'data_type' => 'select',
                'unit' => null,
                'possible_values' => ['ATX', 'Micro-ATX', 'Mini-ITX', 'E-ATX', '2.5"', '3.5"', 'M.2'],
                'applicable_categories' => ['motherboard', 'ssd', 'hdd', 'case'],
                'attribute_group' => 'physical',
                'sort_order' => 230,
                'is_filterable' => true,
                'is_comparable' => true,
            ],

            // Cooling
            [
                'name' => 'Cooling Type',
                'slug' => 'cooling_type',
                'display_name' => 'Cooling Type',
                'description' => 'Type of cooling system',
                'data_type' => 'select',
                'unit' => null,
                'possible_values' => ['Air', 'Liquid', 'Passive', 'Hybrid'],
                'applicable_categories' => ['cpu_cooler', 'gpu', 'case'],
                'attribute_group' => 'cooling',
                'sort_order' => 240,
                'is_filterable' => true,
                'is_comparable' => true,
            ],
        ];

        foreach ($attributes as $attribute) {
            DB::table('attribute_definitions')->insert([
                'attribute_id' => Str::uuid(),
                'name' => $attribute['name'],
                'slug' => $attribute['slug'],
                'display_name' => $attribute['display_name'],
                'description' => $attribute['description'],
                'data_type' => $attribute['data_type'],
                'unit' => $attribute['unit'],
                'validation_rules' => null,
                'possible_values' => isset($attribute['possible_values']) ? json_encode($attribute['possible_values']) : null,
                'applicable_categories' => json_encode($attribute['applicable_categories']),
                'attribute_group' => $attribute['attribute_group'],
                'sort_order' => $attribute['sort_order'],
                'is_active' => true,
                'is_filterable' => $attribute['is_filterable'] ?? false,
                'is_comparable' => $attribute['is_comparable'] ?? true,
                'is_required' => $attribute['is_required'] ?? false,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
